//20101537
#include <stdio.h>
#include <stdlib.h>


int checkP2(int x);
int* dTob(int n, int l);
int bTod(int a[], int l);
int main(){
	int pgs = 4; // Page size
	int ms = 32; // Memory size
	int nof = ms / pgs; // Number of frames
	int offset_bit = checkP2(pgs); // Number of bits required for offset
	int m = checkP2(ms); // Number of address spaces required in main memory
	int pg_num_bit = m - offset_bit; // Number of bits required for page number

	int la[] = {8, 4, 3, 2, 15, 18, 25}; // Logical addresses generated by the CPU
    int pmt[] = {3, 6, 8, 12, 2}; // Page table
    

	printf("Page size: %d\n", pgs);
	printf("Memory size: %d\n", ms);
	printf("Number of frames required: %d\n", nof);
	printf("Page number bits: %d\n", pg_num_bit);
	printf("Offset bits: %d\n", offset_bit);
	printf("Number of address spaces: %d\n", m);
	printf("Page Table_____\n");


	for(int i = 0; i < sizeof(pmt) / sizeof(pmt[0]); i++) {
    	printf("%d -> %d\n", i, pmt[i]);}
    
	for(int i = 0; i < sizeof(la) / sizeof(la[0]); i++) {
    	int logical_address = la[i];
    	int page_number = logical_address >> offset_bit;
    	int offset = logical_address & ((1 << offset_bit) - 1);
   	 
    	int frame_number = pmt[page_number];
        	int physical_address = (frame_number * pgs) + offset;
        	//printf("%d\n", frame_number);
   	 
    	if(page_number >= sizeof(pmt) / sizeof(pmt[0]) || pmt[page_number] == -1 || frame_number==0 ) {
        	printf("%d is an invalid page number \n", page_number);
       	 
    	} else {
       	 
        	if (physical_address < 32) {
            	printf("Corresponding physical address of logical address %d: %d\n", logical_address, physical_address);
           	 
        	} else {
            	printf("%d is an invalid physical address\n", physical_address);
        	}
    	}
	}

	return 0;
}

int checkP2(int x){
	int count = 0;
	while (x > 1){
    	if (x % 2 != 0){
        	return -1;
    	}
    	x /= 2;
    	count++;
	}
	return count;
}

int* dTob(int n, int l){
	static int arr[32];
	for (int i = l - 1; i >= 0; i--){
    	arr[i] = n % 2;
    	n = n / 2;
	}
	return arr;}

int bTod(int a[], int l){
	int decimal = 0;
	for (int i = 0; i < l; i++){
    	decimal += a[i] * (1 << (l - 1 - i));
	}
	return decimal;}

